// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package ferry

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FerryClient is the client API for Ferry service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FerryClient interface {
	StartExportSession(ctx context.Context, in *Target, opts ...grpc.CallOption) (*SessionResponse, error)
	Export(ctx context.Context, opts ...grpc.CallOption) (Ferry_ExportClient, error)
	StopExportSession(ctx context.Context, in *Session, opts ...grpc.CallOption) (*SessionResponse, error)
	GetExportedFile(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (Ferry_GetExportedFileClient, error)
	RemoveExportedFile(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (*FileRequest, error)
	EndExportSession(ctx context.Context, in *Session, opts ...grpc.CallOption) (*SessionResponse, error)
	StartImportSession(ctx context.Context, in *Target, opts ...grpc.CallOption) (*SessionResponse, error)
	Import(ctx context.Context, opts ...grpc.CallOption) (Ferry_ImportClient, error)
	StopImportSession(ctx context.Context, in *Session, opts ...grpc.CallOption) (*SessionResponse, error)
}

type ferryClient struct {
	cc grpc.ClientConnInterface
}

func NewFerryClient(cc grpc.ClientConnInterface) FerryClient {
	return &ferryClient{cc}
}

func (c *ferryClient) StartExportSession(ctx context.Context, in *Target, opts ...grpc.CallOption) (*SessionResponse, error) {
	out := new(SessionResponse)
	err := c.cc.Invoke(ctx, "/ferry.Ferry/StartExportSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ferryClient) Export(ctx context.Context, opts ...grpc.CallOption) (Ferry_ExportClient, error) {
	stream, err := c.cc.NewStream(ctx, &Ferry_ServiceDesc.Streams[0], "/ferry.Ferry/Export", opts...)
	if err != nil {
		return nil, err
	}
	x := &ferryExportClient{stream}
	return x, nil
}

type Ferry_ExportClient interface {
	Send(*KeyRequest) error
	CloseAndRecv() (*SessionResponse, error)
	grpc.ClientStream
}

type ferryExportClient struct {
	grpc.ClientStream
}

func (x *ferryExportClient) Send(m *KeyRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *ferryExportClient) CloseAndRecv() (*SessionResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(SessionResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *ferryClient) StopExportSession(ctx context.Context, in *Session, opts ...grpc.CallOption) (*SessionResponse, error) {
	out := new(SessionResponse)
	err := c.cc.Invoke(ctx, "/ferry.Ferry/StopExportSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ferryClient) GetExportedFile(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (Ferry_GetExportedFileClient, error) {
	stream, err := c.cc.NewStream(ctx, &Ferry_ServiceDesc.Streams[1], "/ferry.Ferry/GetExportedFile", opts...)
	if err != nil {
		return nil, err
	}
	x := &ferryGetExportedFileClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Ferry_GetExportedFileClient interface {
	Recv() (*FileRequestResponse, error)
	grpc.ClientStream
}

type ferryGetExportedFileClient struct {
	grpc.ClientStream
}

func (x *ferryGetExportedFileClient) Recv() (*FileRequestResponse, error) {
	m := new(FileRequestResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *ferryClient) RemoveExportedFile(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (*FileRequest, error) {
	out := new(FileRequest)
	err := c.cc.Invoke(ctx, "/ferry.Ferry/RemoveExportedFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ferryClient) EndExportSession(ctx context.Context, in *Session, opts ...grpc.CallOption) (*SessionResponse, error) {
	out := new(SessionResponse)
	err := c.cc.Invoke(ctx, "/ferry.Ferry/EndExportSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ferryClient) StartImportSession(ctx context.Context, in *Target, opts ...grpc.CallOption) (*SessionResponse, error) {
	out := new(SessionResponse)
	err := c.cc.Invoke(ctx, "/ferry.Ferry/StartImportSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ferryClient) Import(ctx context.Context, opts ...grpc.CallOption) (Ferry_ImportClient, error) {
	stream, err := c.cc.NewStream(ctx, &Ferry_ServiceDesc.Streams[2], "/ferry.Ferry/Import", opts...)
	if err != nil {
		return nil, err
	}
	x := &ferryImportClient{stream}
	return x, nil
}

type Ferry_ImportClient interface {
	Send(*ImportRequest) error
	CloseAndRecv() (*SessionResponse, error)
	grpc.ClientStream
}

type ferryImportClient struct {
	grpc.ClientStream
}

func (x *ferryImportClient) Send(m *ImportRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *ferryImportClient) CloseAndRecv() (*SessionResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(SessionResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *ferryClient) StopImportSession(ctx context.Context, in *Session, opts ...grpc.CallOption) (*SessionResponse, error) {
	out := new(SessionResponse)
	err := c.cc.Invoke(ctx, "/ferry.Ferry/StopImportSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FerryServer is the server API for Ferry service.
// All implementations must embed UnimplementedFerryServer
// for forward compatibility
type FerryServer interface {
	StartExportSession(context.Context, *Target) (*SessionResponse, error)
	Export(Ferry_ExportServer) error
	StopExportSession(context.Context, *Session) (*SessionResponse, error)
	GetExportedFile(*FileRequest, Ferry_GetExportedFileServer) error
	RemoveExportedFile(context.Context, *FileRequest) (*FileRequest, error)
	EndExportSession(context.Context, *Session) (*SessionResponse, error)
	StartImportSession(context.Context, *Target) (*SessionResponse, error)
	Import(Ferry_ImportServer) error
	StopImportSession(context.Context, *Session) (*SessionResponse, error)
	mustEmbedUnimplementedFerryServer()
}

// UnimplementedFerryServer must be embedded to have forward compatible implementations.
type UnimplementedFerryServer struct {
}

func (UnimplementedFerryServer) StartExportSession(context.Context, *Target) (*SessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartExportSession not implemented")
}
func (UnimplementedFerryServer) Export(Ferry_ExportServer) error {
	return status.Errorf(codes.Unimplemented, "method Export not implemented")
}
func (UnimplementedFerryServer) StopExportSession(context.Context, *Session) (*SessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopExportSession not implemented")
}
func (UnimplementedFerryServer) GetExportedFile(*FileRequest, Ferry_GetExportedFileServer) error {
	return status.Errorf(codes.Unimplemented, "method GetExportedFile not implemented")
}
func (UnimplementedFerryServer) RemoveExportedFile(context.Context, *FileRequest) (*FileRequest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveExportedFile not implemented")
}
func (UnimplementedFerryServer) EndExportSession(context.Context, *Session) (*SessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EndExportSession not implemented")
}
func (UnimplementedFerryServer) StartImportSession(context.Context, *Target) (*SessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartImportSession not implemented")
}
func (UnimplementedFerryServer) Import(Ferry_ImportServer) error {
	return status.Errorf(codes.Unimplemented, "method Import not implemented")
}
func (UnimplementedFerryServer) StopImportSession(context.Context, *Session) (*SessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopImportSession not implemented")
}
func (UnimplementedFerryServer) mustEmbedUnimplementedFerryServer() {}

// UnsafeFerryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FerryServer will
// result in compilation errors.
type UnsafeFerryServer interface {
	mustEmbedUnimplementedFerryServer()
}

func RegisterFerryServer(s grpc.ServiceRegistrar, srv FerryServer) {
	s.RegisterService(&Ferry_ServiceDesc, srv)
}

func _Ferry_StartExportSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Target)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FerryServer).StartExportSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ferry.Ferry/StartExportSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FerryServer).StartExportSession(ctx, req.(*Target))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ferry_Export_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FerryServer).Export(&ferryExportServer{stream})
}

type Ferry_ExportServer interface {
	SendAndClose(*SessionResponse) error
	Recv() (*KeyRequest, error)
	grpc.ServerStream
}

type ferryExportServer struct {
	grpc.ServerStream
}

func (x *ferryExportServer) SendAndClose(m *SessionResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *ferryExportServer) Recv() (*KeyRequest, error) {
	m := new(KeyRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Ferry_StopExportSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Session)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FerryServer).StopExportSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ferry.Ferry/StopExportSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FerryServer).StopExportSession(ctx, req.(*Session))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ferry_GetExportedFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FileRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FerryServer).GetExportedFile(m, &ferryGetExportedFileServer{stream})
}

type Ferry_GetExportedFileServer interface {
	Send(*FileRequestResponse) error
	grpc.ServerStream
}

type ferryGetExportedFileServer struct {
	grpc.ServerStream
}

func (x *ferryGetExportedFileServer) Send(m *FileRequestResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Ferry_RemoveExportedFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FerryServer).RemoveExportedFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ferry.Ferry/RemoveExportedFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FerryServer).RemoveExportedFile(ctx, req.(*FileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ferry_EndExportSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Session)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FerryServer).EndExportSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ferry.Ferry/EndExportSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FerryServer).EndExportSession(ctx, req.(*Session))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ferry_StartImportSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Target)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FerryServer).StartImportSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ferry.Ferry/StartImportSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FerryServer).StartImportSession(ctx, req.(*Target))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ferry_Import_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FerryServer).Import(&ferryImportServer{stream})
}

type Ferry_ImportServer interface {
	SendAndClose(*SessionResponse) error
	Recv() (*ImportRequest, error)
	grpc.ServerStream
}

type ferryImportServer struct {
	grpc.ServerStream
}

func (x *ferryImportServer) SendAndClose(m *SessionResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *ferryImportServer) Recv() (*ImportRequest, error) {
	m := new(ImportRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Ferry_StopImportSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Session)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FerryServer).StopImportSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ferry.Ferry/StopImportSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FerryServer).StopImportSession(ctx, req.(*Session))
	}
	return interceptor(ctx, in, info, handler)
}

// Ferry_ServiceDesc is the grpc.ServiceDesc for Ferry service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Ferry_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ferry.Ferry",
	HandlerType: (*FerryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartExportSession",
			Handler:    _Ferry_StartExportSession_Handler,
		},
		{
			MethodName: "StopExportSession",
			Handler:    _Ferry_StopExportSession_Handler,
		},
		{
			MethodName: "RemoveExportedFile",
			Handler:    _Ferry_RemoveExportedFile_Handler,
		},
		{
			MethodName: "EndExportSession",
			Handler:    _Ferry_EndExportSession_Handler,
		},
		{
			MethodName: "StartImportSession",
			Handler:    _Ferry_StartImportSession_Handler,
		},
		{
			MethodName: "StopImportSession",
			Handler:    _Ferry_StopImportSession_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Export",
			Handler:       _Ferry_Export_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "GetExportedFile",
			Handler:       _Ferry_GetExportedFile_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Import",
			Handler:       _Ferry_Import_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "ferry.proto",
}
