// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ferry.proto

package ferry

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type KeyRangeResponse_OpStatus int32

const (
	KeyRangeResponse_SUCCESS   KeyRangeResponse_OpStatus = 0
	KeyRangeResponse_FAILURE   KeyRangeResponse_OpStatus = 1
	KeyRangeResponse_TRANSIENT KeyRangeResponse_OpStatus = 2
)

var KeyRangeResponse_OpStatus_name = map[int32]string{
	0: "SUCCESS",
	1: "FAILURE",
	2: "TRANSIENT",
}

var KeyRangeResponse_OpStatus_value = map[string]int32{
	"SUCCESS":   0,
	"FAILURE":   1,
	"TRANSIENT": 2,
}

func (x KeyRangeResponse_OpStatus) String() string {
	return proto.EnumName(KeyRangeResponse_OpStatus_name, int32(x))
}

func (KeyRangeResponse_OpStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fe9230b79525d794, []int{6, 0}
}

type SessionResponse_OpStatus int32

const (
	SessionResponse_SUCCESS SessionResponse_OpStatus = 0
	SessionResponse_FAILURE SessionResponse_OpStatus = 1
)

var SessionResponse_OpStatus_name = map[int32]string{
	0: "SUCCESS",
	1: "FAILURE",
}

var SessionResponse_OpStatus_value = map[string]int32{
	"SUCCESS": 0,
	"FAILURE": 1,
}

func (x SessionResponse_OpStatus) String() string {
	return proto.EnumName(SessionResponse_OpStatus_name, int32(x))
}

func (SessionResponse_OpStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fe9230b79525d794, []int{8, 0}
}

type SessionResponse_SessionState int32

const (
	SessionResponse_STARTED SessionResponse_SessionState = 0
	SessionResponse_STOPPED SessionResponse_SessionState = 1
	SessionResponse_ENDED   SessionResponse_SessionState = 2
)

var SessionResponse_SessionState_name = map[int32]string{
	0: "STARTED",
	1: "STOPPED",
	2: "ENDED",
}

var SessionResponse_SessionState_value = map[string]int32{
	"STARTED": 0,
	"STOPPED": 1,
	"ENDED":   2,
}

func (x SessionResponse_SessionState) String() string {
	return proto.EnumName(SessionResponse_SessionState_name, int32(x))
}

func (SessionResponse_SessionState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fe9230b79525d794, []int{8, 1}
}

type ImportRequest struct {
	FileName             string   `protobuf:"bytes,1,opt,name=fileName,proto3" json:"fileName,omitempty"`
	SessionId            string   `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImportRequest) Reset()         { *m = ImportRequest{} }
func (m *ImportRequest) String() string { return proto.CompactTextString(m) }
func (*ImportRequest) ProtoMessage()    {}
func (*ImportRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe9230b79525d794, []int{0}
}

func (m *ImportRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImportRequest.Unmarshal(m, b)
}
func (m *ImportRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImportRequest.Marshal(b, m, deterministic)
}
func (m *ImportRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImportRequest.Merge(m, src)
}
func (m *ImportRequest) XXX_Size() int {
	return xxx_messageInfo_ImportRequest.Size(m)
}
func (m *ImportRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ImportRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ImportRequest proto.InternalMessageInfo

func (m *ImportRequest) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *ImportRequest) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

type FileRequest struct {
	SessionId            string   `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TargetUrl            string   `protobuf:"bytes,2,opt,name=target_url,json=targetUrl,proto3" json:"target_url,omitempty"`
	FileName             string   `protobuf:"bytes,3,opt,name=fileName,proto3" json:"fileName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileRequest) Reset()         { *m = FileRequest{} }
func (m *FileRequest) String() string { return proto.CompactTextString(m) }
func (*FileRequest) ProtoMessage()    {}
func (*FileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe9230b79525d794, []int{1}
}

func (m *FileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileRequest.Unmarshal(m, b)
}
func (m *FileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileRequest.Marshal(b, m, deterministic)
}
func (m *FileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileRequest.Merge(m, src)
}
func (m *FileRequest) XXX_Size() int {
	return xxx_messageInfo_FileRequest.Size(m)
}
func (m *FileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FileRequest proto.InternalMessageInfo

func (m *FileRequest) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *FileRequest) GetTargetUrl() string {
	if m != nil {
		return m.TargetUrl
	}
	return ""
}

func (m *FileRequest) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

type FileRequestResponse struct {
	FileName             string   `protobuf:"bytes,1,opt,name=fileName,proto3" json:"fileName,omitempty"`
	BlockNum             int32    `protobuf:"varint,2,opt,name=blockNum,proto3" json:"blockNum,omitempty"`
	BlockData            []byte   `protobuf:"bytes,3,opt,name=blockData,proto3" json:"blockData,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileRequestResponse) Reset()         { *m = FileRequestResponse{} }
func (m *FileRequestResponse) String() string { return proto.CompactTextString(m) }
func (*FileRequestResponse) ProtoMessage()    {}
func (*FileRequestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe9230b79525d794, []int{2}
}

func (m *FileRequestResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileRequestResponse.Unmarshal(m, b)
}
func (m *FileRequestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileRequestResponse.Marshal(b, m, deterministic)
}
func (m *FileRequestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileRequestResponse.Merge(m, src)
}
func (m *FileRequestResponse) XXX_Size() int {
	return xxx_messageInfo_FileRequestResponse.Size(m)
}
func (m *FileRequestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FileRequestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FileRequestResponse proto.InternalMessageInfo

func (m *FileRequestResponse) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *FileRequestResponse) GetBlockNum() int32 {
	if m != nil {
		return m.BlockNum
	}
	return 0
}

func (m *FileRequestResponse) GetBlockData() []byte {
	if m != nil {
		return m.BlockData
	}
	return nil
}

type Time struct {
	Ts                   int64    `protobuf:"varint,1,opt,name=ts,proto3" json:"ts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Time) Reset()         { *m = Time{} }
func (m *Time) String() string { return proto.CompactTextString(m) }
func (*Time) ProtoMessage()    {}
func (*Time) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe9230b79525d794, []int{3}
}

func (m *Time) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Time.Unmarshal(m, b)
}
func (m *Time) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Time.Marshal(b, m, deterministic)
}
func (m *Time) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Time.Merge(m, src)
}
func (m *Time) XXX_Size() int {
	return xxx_messageInfo_Time.Size(m)
}
func (m *Time) XXX_DiscardUnknown() {
	xxx_messageInfo_Time.DiscardUnknown(m)
}

var xxx_messageInfo_Time proto.InternalMessageInfo

func (m *Time) GetTs() int64 {
	if m != nil {
		return m.Ts
	}
	return 0
}

type Target struct {
	TargetUrl            string   `protobuf:"bytes,1,opt,name=target_url,json=targetUrl,proto3" json:"target_url,omitempty"`
	ReaderThreads        int32    `protobuf:"varint,2,opt,name=readerThreads,proto3" json:"readerThreads,omitempty"`
	Compress             bool     `protobuf:"varint,3,opt,name=compress,proto3" json:"compress,omitempty"`
	SamplingMode         bool     `protobuf:"varint,4,opt,name=samplingMode,proto3" json:"samplingMode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Target) Reset()         { *m = Target{} }
func (m *Target) String() string { return proto.CompactTextString(m) }
func (*Target) ProtoMessage()    {}
func (*Target) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe9230b79525d794, []int{4}
}

func (m *Target) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Target.Unmarshal(m, b)
}
func (m *Target) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Target.Marshal(b, m, deterministic)
}
func (m *Target) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Target.Merge(m, src)
}
func (m *Target) XXX_Size() int {
	return xxx_messageInfo_Target.Size(m)
}
func (m *Target) XXX_DiscardUnknown() {
	xxx_messageInfo_Target.DiscardUnknown(m)
}

var xxx_messageInfo_Target proto.InternalMessageInfo

func (m *Target) GetTargetUrl() string {
	if m != nil {
		return m.TargetUrl
	}
	return ""
}

func (m *Target) GetReaderThreads() int32 {
	if m != nil {
		return m.ReaderThreads
	}
	return 0
}

func (m *Target) GetCompress() bool {
	if m != nil {
		return m.Compress
	}
	return false
}

func (m *Target) GetSamplingMode() bool {
	if m != nil {
		return m.SamplingMode
	}
	return false
}

type KeyRequest struct {
	Begin                []byte   `protobuf:"bytes,1,opt,name=begin,proto3" json:"begin,omitempty"`
	End                  []byte   `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	SessionId            string   `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyRequest) Reset()         { *m = KeyRequest{} }
func (m *KeyRequest) String() string { return proto.CompactTextString(m) }
func (*KeyRequest) ProtoMessage()    {}
func (*KeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe9230b79525d794, []int{5}
}

func (m *KeyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyRequest.Unmarshal(m, b)
}
func (m *KeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyRequest.Marshal(b, m, deterministic)
}
func (m *KeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyRequest.Merge(m, src)
}
func (m *KeyRequest) XXX_Size() int {
	return xxx_messageInfo_KeyRequest.Size(m)
}
func (m *KeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_KeyRequest proto.InternalMessageInfo

func (m *KeyRequest) GetBegin() []byte {
	if m != nil {
		return m.Begin
	}
	return nil
}

func (m *KeyRequest) GetEnd() []byte {
	if m != nil {
		return m.End
	}
	return nil
}

func (m *KeyRequest) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

type KeyRangeResponse struct {
	BeginKey             []byte                    `protobuf:"bytes,1,opt,name=begin_key,json=beginKey,proto3" json:"begin_key,omitempty"`
	EndKey               []byte                    `protobuf:"bytes,2,opt,name=end_key,json=endKey,proto3" json:"end_key,omitempty"`
	StartTime            int64                     `protobuf:"varint,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime              int64                     `protobuf:"varint,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Status               KeyRangeResponse_OpStatus `protobuf:"varint,5,opt,name=status,proto3,enum=ferry.KeyRangeResponse_OpStatus" json:"status,omitempty"`
	FileUrl              string                    `protobuf:"bytes,6,opt,name=file_url,json=fileUrl,proto3" json:"file_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *KeyRangeResponse) Reset()         { *m = KeyRangeResponse{} }
func (m *KeyRangeResponse) String() string { return proto.CompactTextString(m) }
func (*KeyRangeResponse) ProtoMessage()    {}
func (*KeyRangeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe9230b79525d794, []int{6}
}

func (m *KeyRangeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyRangeResponse.Unmarshal(m, b)
}
func (m *KeyRangeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyRangeResponse.Marshal(b, m, deterministic)
}
func (m *KeyRangeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyRangeResponse.Merge(m, src)
}
func (m *KeyRangeResponse) XXX_Size() int {
	return xxx_messageInfo_KeyRangeResponse.Size(m)
}
func (m *KeyRangeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyRangeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_KeyRangeResponse proto.InternalMessageInfo

func (m *KeyRangeResponse) GetBeginKey() []byte {
	if m != nil {
		return m.BeginKey
	}
	return nil
}

func (m *KeyRangeResponse) GetEndKey() []byte {
	if m != nil {
		return m.EndKey
	}
	return nil
}

func (m *KeyRangeResponse) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *KeyRangeResponse) GetEndTime() int64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

func (m *KeyRangeResponse) GetStatus() KeyRangeResponse_OpStatus {
	if m != nil {
		return m.Status
	}
	return KeyRangeResponse_SUCCESS
}

func (m *KeyRangeResponse) GetFileUrl() string {
	if m != nil {
		return m.FileUrl
	}
	return ""
}

type FinalizedFile struct {
	FileName             string   `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	Checksum             string   `protobuf:"bytes,4,opt,name=checksum,proto3" json:"checksum,omitempty"`
	ContentSize          int64    `protobuf:"varint,2,opt,name=content_size,json=contentSize,proto3" json:"content_size,omitempty"`
	ChunksCount          int64    `protobuf:"varint,3,opt,name=chunks_count,json=chunksCount,proto3" json:"chunks_count,omitempty"`
	ShellOnly            bool     `protobuf:"varint,5,opt,name=shell_only,json=shellOnly,proto3" json:"shell_only,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FinalizedFile) Reset()         { *m = FinalizedFile{} }
func (m *FinalizedFile) String() string { return proto.CompactTextString(m) }
func (*FinalizedFile) ProtoMessage()    {}
func (*FinalizedFile) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe9230b79525d794, []int{7}
}

func (m *FinalizedFile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FinalizedFile.Unmarshal(m, b)
}
func (m *FinalizedFile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FinalizedFile.Marshal(b, m, deterministic)
}
func (m *FinalizedFile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FinalizedFile.Merge(m, src)
}
func (m *FinalizedFile) XXX_Size() int {
	return xxx_messageInfo_FinalizedFile.Size(m)
}
func (m *FinalizedFile) XXX_DiscardUnknown() {
	xxx_messageInfo_FinalizedFile.DiscardUnknown(m)
}

var xxx_messageInfo_FinalizedFile proto.InternalMessageInfo

func (m *FinalizedFile) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *FinalizedFile) GetChecksum() string {
	if m != nil {
		return m.Checksum
	}
	return ""
}

func (m *FinalizedFile) GetContentSize() int64 {
	if m != nil {
		return m.ContentSize
	}
	return 0
}

func (m *FinalizedFile) GetChunksCount() int64 {
	if m != nil {
		return m.ChunksCount
	}
	return 0
}

func (m *FinalizedFile) GetShellOnly() bool {
	if m != nil {
		return m.ShellOnly
	}
	return false
}

type SessionResponse struct {
	Status               SessionResponse_OpStatus     `protobuf:"varint,1,opt,name=status,proto3,enum=ferry.SessionResponse_OpStatus" json:"status,omitempty"`
	State                SessionResponse_SessionState `protobuf:"varint,2,opt,name=state,proto3,enum=ferry.SessionResponse_SessionState" json:"state,omitempty"`
	SessionId            string                       `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ErrorDetails         string                       `protobuf:"bytes,4,opt,name=error_details,json=errorDetails,proto3" json:"error_details,omitempty"`
	FinalizedFiles       []*FinalizedFile             `protobuf:"bytes,5,rep,name=finalized_files,json=finalizedFiles,proto3" json:"finalized_files,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *SessionResponse) Reset()         { *m = SessionResponse{} }
func (m *SessionResponse) String() string { return proto.CompactTextString(m) }
func (*SessionResponse) ProtoMessage()    {}
func (*SessionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe9230b79525d794, []int{8}
}

func (m *SessionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionResponse.Unmarshal(m, b)
}
func (m *SessionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionResponse.Marshal(b, m, deterministic)
}
func (m *SessionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionResponse.Merge(m, src)
}
func (m *SessionResponse) XXX_Size() int {
	return xxx_messageInfo_SessionResponse.Size(m)
}
func (m *SessionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SessionResponse proto.InternalMessageInfo

func (m *SessionResponse) GetStatus() SessionResponse_OpStatus {
	if m != nil {
		return m.Status
	}
	return SessionResponse_SUCCESS
}

func (m *SessionResponse) GetState() SessionResponse_SessionState {
	if m != nil {
		return m.State
	}
	return SessionResponse_STARTED
}

func (m *SessionResponse) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *SessionResponse) GetErrorDetails() string {
	if m != nil {
		return m.ErrorDetails
	}
	return ""
}

func (m *SessionResponse) GetFinalizedFiles() []*FinalizedFile {
	if m != nil {
		return m.FinalizedFiles
	}
	return nil
}

type Session struct {
	SessionId            string   `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Session) Reset()         { *m = Session{} }
func (m *Session) String() string { return proto.CompactTextString(m) }
func (*Session) ProtoMessage()    {}
func (*Session) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe9230b79525d794, []int{9}
}

func (m *Session) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Session.Unmarshal(m, b)
}
func (m *Session) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Session.Marshal(b, m, deterministic)
}
func (m *Session) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Session.Merge(m, src)
}
func (m *Session) XXX_Size() int {
	return xxx_messageInfo_Session.Size(m)
}
func (m *Session) XXX_DiscardUnknown() {
	xxx_messageInfo_Session.DiscardUnknown(m)
}

var xxx_messageInfo_Session proto.InternalMessageInfo

func (m *Session) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func init() {
	proto.RegisterEnum("ferry.KeyRangeResponse_OpStatus", KeyRangeResponse_OpStatus_name, KeyRangeResponse_OpStatus_value)
	proto.RegisterEnum("ferry.SessionResponse_OpStatus", SessionResponse_OpStatus_name, SessionResponse_OpStatus_value)
	proto.RegisterEnum("ferry.SessionResponse_SessionState", SessionResponse_SessionState_name, SessionResponse_SessionState_value)
	proto.RegisterType((*ImportRequest)(nil), "ferry.ImportRequest")
	proto.RegisterType((*FileRequest)(nil), "ferry.FileRequest")
	proto.RegisterType((*FileRequestResponse)(nil), "ferry.FileRequestResponse")
	proto.RegisterType((*Time)(nil), "ferry.Time")
	proto.RegisterType((*Target)(nil), "ferry.Target")
	proto.RegisterType((*KeyRequest)(nil), "ferry.KeyRequest")
	proto.RegisterType((*KeyRangeResponse)(nil), "ferry.KeyRangeResponse")
	proto.RegisterType((*FinalizedFile)(nil), "ferry.FinalizedFile")
	proto.RegisterType((*SessionResponse)(nil), "ferry.SessionResponse")
	proto.RegisterType((*Session)(nil), "ferry.Session")
}

func init() { proto.RegisterFile("ferry.proto", fileDescriptor_fe9230b79525d794) }

var fileDescriptor_fe9230b79525d794 = []byte{
	// 842 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0xdb, 0x72, 0xe3, 0x44,
	0x10, 0x8d, 0xec, 0xd8, 0xb1, 0xda, 0x97, 0x78, 0x87, 0xad, 0x25, 0x18, 0x28, 0x82, 0x76, 0x1f,
	0xfc, 0x94, 0x50, 0xc9, 0x03, 0x97, 0x22, 0x54, 0x85, 0x58, 0xa1, 0xc2, 0x82, 0xb3, 0x35, 0x72,
	0x5e, 0x78, 0x51, 0xc9, 0x56, 0xc7, 0x56, 0x59, 0x1a, 0x19, 0xcd, 0x98, 0xc2, 0xf9, 0x06, 0xf8,
	0x14, 0x3e, 0x81, 0xaf, 0xe1, 0x47, 0xa8, 0xe9, 0x91, 0xb5, 0x96, 0x77, 0x73, 0x81, 0x27, 0x4f,
	0x9f, 0xbe, 0x9d, 0x39, 0xdd, 0x1e, 0x41, 0xf3, 0x16, 0xb3, 0x6c, 0x75, 0xb4, 0xc8, 0x52, 0x95,
	0xb2, 0x1a, 0x19, 0xce, 0x8f, 0xd0, 0xbe, 0x4a, 0x16, 0x69, 0xa6, 0x38, 0xfe, 0xba, 0x44, 0xa9,
	0x58, 0x0f, 0x1a, 0xb7, 0x51, 0x8c, 0xc3, 0x20, 0xc1, 0x03, 0xeb, 0xd0, 0xea, 0xdb, 0xbc, 0xb0,
	0xd9, 0xa7, 0x00, 0x12, 0xa5, 0x8c, 0x52, 0xe1, 0x47, 0xe1, 0x41, 0x85, 0xbc, 0x76, 0x8e, 0x5c,
	0x85, 0xce, 0x14, 0x9a, 0x97, 0x51, 0x8c, 0xeb, 0x4a, 0xe5, 0x68, 0x6b, 0x2b, 0x5a, 0xbb, 0x55,
	0x90, 0x4d, 0x51, 0xf9, 0xcb, 0x2c, 0x5e, 0x17, 0x33, 0xc8, 0x4d, 0x16, 0x97, 0x78, 0x54, 0xcb,
	0x3c, 0x9c, 0x39, 0x7c, 0xb0, 0xd1, 0x88, 0xa3, 0x5c, 0xa4, 0x42, 0xe2, 0x83, 0xd4, 0x7b, 0xd0,
	0x18, 0xc7, 0xe9, 0x64, 0x3e, 0x5c, 0x26, 0xd4, 0xab, 0xc6, 0x0b, 0x9b, 0x7d, 0x02, 0x36, 0x9d,
	0x07, 0x81, 0x0a, 0xa8, 0x57, 0x8b, 0xbf, 0x05, 0x9c, 0x17, 0xb0, 0x3b, 0x8a, 0x12, 0x64, 0x1d,
	0xa8, 0x28, 0x49, 0x75, 0xab, 0xbc, 0xa2, 0xa4, 0xf3, 0xa7, 0x05, 0xf5, 0x11, 0xd1, 0xdd, 0xba,
	0x8a, 0xb5, 0x7d, 0x95, 0x57, 0xd0, 0xce, 0x30, 0x08, 0x31, 0x1b, 0xcd, 0xf4, 0xaf, 0xcc, 0x09,
	0x94, 0x41, 0xcd, 0x70, 0x92, 0x26, 0x8b, 0x0c, 0xa5, 0x24, 0x12, 0x0d, 0x5e, 0xd8, 0xcc, 0x81,
	0x96, 0x0c, 0x92, 0x45, 0x1c, 0x89, 0xe9, 0xcf, 0x69, 0x88, 0x07, 0xbb, 0xe4, 0x2f, 0x61, 0x8e,
	0x07, 0xf0, 0x1a, 0x57, 0x6b, 0xf1, 0x9f, 0x43, 0x6d, 0x8c, 0xd3, 0x48, 0x10, 0x9b, 0x16, 0x37,
	0x06, 0xeb, 0x42, 0x15, 0x85, 0x99, 0x5c, 0x8b, 0xeb, 0xe3, 0xd6, 0x90, 0xaa, 0xdb, 0x23, 0xfd,
	0xa3, 0x02, 0x5d, 0x5d, 0x35, 0x10, 0x53, 0x2c, 0x74, 0xfe, 0x18, 0x6c, 0x2a, 0xe7, 0xcf, 0x71,
	0x95, 0xd7, 0x6f, 0x10, 0xf0, 0x1a, 0x57, 0xec, 0x43, 0xd8, 0x43, 0x11, 0x92, 0xcb, 0xb4, 0xa9,
	0xa3, 0x08, 0xb5, 0x43, 0x77, 0x52, 0x41, 0xa6, 0x7c, 0x15, 0xe5, 0x23, 0xad, 0x72, 0x9b, 0x10,
	0x92, 0xf7, 0x23, 0x68, 0xe8, 0x3c, 0x72, 0xee, 0x92, 0x53, 0xd7, 0x21, 0xd7, 0x57, 0x50, 0x97,
	0x2a, 0x50, 0x4b, 0x79, 0x50, 0x3b, 0xb4, 0xfa, 0x9d, 0x93, 0xc3, 0x23, 0xb3, 0xc8, 0xdb, 0xc4,
	0x8e, 0xae, 0x17, 0x1e, 0xc5, 0xf1, 0x3c, 0x5e, 0x17, 0xd5, 0x1b, 0x40, 0x63, 0xa9, 0xd3, 0xdd,
	0xf6, 0xb4, 0x7d, 0x93, 0xc5, 0xce, 0x29, 0x34, 0xd6, 0xe1, 0xac, 0x09, 0x7b, 0xde, 0xcd, 0xc5,
	0x85, 0xeb, 0x79, 0xdd, 0x1d, 0x6d, 0x5c, 0x9e, 0x5f, 0xfd, 0x74, 0xc3, 0xdd, 0xae, 0xc5, 0xda,
	0x60, 0x8f, 0xf8, 0xf9, 0xd0, 0xbb, 0x72, 0x87, 0xa3, 0x6e, 0xc5, 0xf9, 0xcb, 0x82, 0xf6, 0x65,
	0x24, 0x82, 0x38, 0xba, 0xc3, 0x50, 0xaf, 0xa0, 0xd6, 0x82, 0x3a, 0x88, 0x7b, 0x96, 0x6e, 0x32,
	0xc3, 0xc9, 0x5c, 0x2e, 0x13, 0xba, 0x93, 0xcd, 0x0b, 0x9b, 0x7d, 0x0e, 0xad, 0x49, 0x2a, 0x14,
	0x0a, 0xe5, 0xcb, 0xe8, 0x0e, 0x49, 0xac, 0x2a, 0x6f, 0xe6, 0x98, 0x17, 0xdd, 0x21, 0x85, 0xcc,
	0x96, 0x62, 0x2e, 0xfd, 0x49, 0xba, 0x14, 0x2a, 0xd7, 0xac, 0x69, 0xb0, 0x0b, 0x0d, 0x91, 0xa8,
	0x33, 0x8c, 0x63, 0x3f, 0x15, 0xf1, 0x8a, 0xe4, 0x69, 0x70, 0x9b, 0x90, 0x6b, 0x11, 0xaf, 0x9c,
	0x7f, 0x2a, 0xb0, 0xef, 0x99, 0x61, 0x16, 0xd3, 0xfb, 0xb2, 0x50, 0xd3, 0x22, 0x35, 0x3f, 0xcb,
	0xd5, 0xdc, 0x8a, 0x7b, 0x57, 0xcc, 0xaf, 0xa1, 0xa6, 0x4f, 0x86, 0x6a, 0xe7, 0xe4, 0xe5, 0x3d,
	0x79, 0xb9, 0xad, 0x93, 0x91, 0x9b, 0x8c, 0x47, 0xb6, 0x8c, 0xbd, 0x84, 0x36, 0x66, 0x59, 0x9a,
	0xf9, 0x21, 0xaa, 0x20, 0x8a, 0x65, 0x2e, 0x56, 0x8b, 0xc0, 0x81, 0xc1, 0xd8, 0x19, 0xec, 0xdf,
	0xae, 0xa5, 0xf7, 0xb5, 0xc4, 0x7a, 0x1d, 0xaa, 0xfd, 0xe6, 0xc9, 0xf3, 0x9c, 0x48, 0x69, 0x30,
	0xbc, 0x73, 0xbb, 0x69, 0x4a, 0xe7, 0xd5, 0x53, 0xe6, 0xed, 0x9c, 0x42, 0x6b, 0x93, 0x3f, 0x45,
	0x8e, 0xce, 0xf9, 0xc8, 0x1d, 0x98, 0x48, 0x6f, 0x74, 0xfd, 0xe6, 0x8d, 0x3b, 0xe8, 0x5a, 0xcc,
	0x86, 0x9a, 0x3b, 0x1c, 0xb8, 0x83, 0x6e, 0xc5, 0xe9, 0xc3, 0x5e, 0x9e, 0xf4, 0xc8, 0x9b, 0x77,
	0xf2, 0xf7, 0x2e, 0xd4, 0x2e, 0x35, 0x59, 0x76, 0x06, 0xcc, 0xd3, 0xbb, 0xef, 0xfe, 0xae, 0x1f,
	0xdf, 0x75, 0x7a, 0x3b, 0xbf, 0x8a, 0x79, 0x57, 0x7a, 0x2f, 0xde, 0x2f, 0xb1, 0xb3, 0xa3, 0x87,
	0x68, 0x32, 0xd9, 0xb3, 0x8d, 0x3f, 0x83, 0xf9, 0xef, 0xdf, 0x9f, 0xd6, 0xb7, 0xd8, 0x19, 0x3c,
	0xf3, 0x54, 0xba, 0x28, 0xb7, 0xed, 0x94, 0x13, 0x1e, 0xe8, 0xeb, 0xc2, 0xfe, 0x0f, 0x98, 0x93,
	0xce, 0xff, 0x01, 0xac, 0x90, 0xbf, 0x78, 0x91, 0x7b, 0xbd, 0x77, 0xb1, 0xb7, 0x45, 0xbe, 0xb0,
	0xd8, 0x77, 0xc0, 0x38, 0x26, 0xe9, 0x6f, 0xf8, 0x68, 0xa5, 0xf7, 0x60, 0xce, 0x0e, 0xfb, 0x16,
	0xba, 0xae, 0x08, 0xff, 0xef, 0x25, 0xd6, 0xda, 0x9b, 0x0f, 0xdf, 0x7f, 0xd6, 0xfe, 0x1b, 0xa8,
	0x9b, 0x4c, 0xb6, 0xde, 0xbc, 0xd2, 0x17, 0xf4, 0x29, 0xf2, 0x97, 0x3b, 0x3f, 0x99, 0xf9, 0xf7,
	0xce, 0x2f, 0x87, 0xd3, 0x48, 0xcd, 0x96, 0xe3, 0xa3, 0x49, 0x9a, 0x1c, 0x07, 0x61, 0x3a, 0xc6,
	0x63, 0x8a, 0x3d, 0x8e, 0xa3, 0xb1, 0x39, 0x8d, 0xeb, 0xf4, 0x7d, 0x3f, 0xfd, 0x37, 0x00, 0x00,
	0xff, 0xff, 0x6b, 0x05, 0x72, 0x6e, 0xee, 0x07, 0x00, 0x00,
}
