# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  #push:
  #  branches: [ "master" ]
  #pull_request:
  #  branches: [ "master" ]
  workflow_dispatch:

jobs:

  build:
    runs-on: macos-latest-xlarge
    steps:
    - uses: actions/checkout@v3
      id: release-branch-checkout
      with:
        # Include tags by using fetch-depth=0
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.21
