# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  #push:
  #  branches: [ "master" ]
  #pull_request:
  #  branches: [ "master" ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    # Identify latest tag
    - name: Identify the latest tag
      id: identify-tag
      run: |
        git tag --sort=taggerdate | tail -1
        echo "RELEASE_TAG=$(git tag --sort=taggerdate | tail -1)" >> $GITHUB_ENV

    - name: Build
      run: |
        wget -q https://github.com/apple/foundationdb/releases/download/7.1.15/foundationdb-clients_7.1.15-1_amd64.deb
        sudo dpkg -i foundationdb-clients_7.1.15-1_amd64.deb
        rm -fv foundationdb-clients_7.1.15-1_amd64.deb
        go build -v ./...
        tar cvzf ferry.x86_64.tar.gz ferry .ferry.yaml

    - name: Test
      run: go test -v ./...
      
    - name: release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.RELEASE_TAG }}
        files: |
           ferry.x86_64.tar.gz
